---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "image-mapper.fullname" . }}-config
  labels:
    {{- include "image-mapper.labels" . | nindent 4 }}
data:
  mapping.json: |-
    {{- .Values.mapping | toJson | nindent 4 }}
