---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-mapper.fullname" . }}
  labels:
    {{- include "image-mapper.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      targetPort: {{ .Values.service.targetPort }}
      name: {{ .Values.service.name | default "https" }}
  selector:
    {{- include "image-mapper.selectorLabels" . | nindent 4 }}
